#!/usr/bin/env bash

xfconf-query -n -c thunar -p /last-view -t string --set "ThunarDetailsView"

xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Shift><Super>parenleft" -t string --set "pamixer --decrease 3"
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Shift><Super>parenright" -t string --set "pamixer --increase 3"
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>e" -t string --set "sh -c 'exec \$EDITOR'"
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>m" -t string --set "xfce4-popup-whiskermenu"
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>f" -t string --set "thunar"
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/commands/custom/<Super>period" -t string --set "rofi -show emoji"

xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>h" -t string --set "prev_workspace_key"
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>j" -t string --set "cycle_windows_key"
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>k" -t string --set "cycle_reverse_windows_key"
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>l" -t string --set "next_workspace_key"
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>q" -t string --set "close_window_key"

xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>1" -t string --set "workspace_1_key"
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>2" -t string --set "workspace_2_key"
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>3" -t string --set "workspace_3_key"
xfconf-query -n -c xfce4-keyboard-shortcuts -p "/xfwm4/custom/<Super>4" -t string --set "workspace_4_key"

xfconf-query -n -c xfwm4 -p "/general/workspace_count" -t int --set 4
xfconf-query -n -c xfwm4 -p "/general/theme" -t string --set "Lead95"
xfconf-query -n -c xfwm4 -p "/general/title_font" -t string --set "Sans Bold 8"

xfconf-query -n -c xfwm4 -p /general/click_to_focus -t bool --set false

xfconf-query -n -c keyboards -p /Default/KeyRepeat/Delay -t int --set 250
xfconf-query -n -c keyboards -p /Default/KeyRepeat/Rate -t int --set 40
