(require 'autothemer)

(defmacro battery-deftheme (name description greys contrasts)
  `(autothemer-deftheme
    ,name
    ,description
    ,(append
      '((((class color) (min-colors #xFFFFFF))))
      '((neutral0  "#101010")
        (neutral1  "#191919")
        (neutral2  "#262524")
        (neutral3  "#353231")
        (neutral4  "#403c3a")
        (neutral5  "#504845")
        (neutral6  "#635852")
        (neutral7  "#7b6c61")
        (neutral8  "#958172")
        (neutral9  "#a89984")
        (neutral10 "#bdae93")
        (neutral11 "#d2c3a5")
        (neutral12 "#e7d8b3")
        (neutral13 "#f2e4ba")
        (neutral14 "#faedc9")
        (neutral15 "#fef5d8"))
      greys
      '((darker-red      "#67191b")
        (darker-orange   "#572e1a")
        (darker-yellow   "#423818")
        (darker-olive    "#302f16")
        (darker-green    "#183815")
        (darker-cyan     "#1a2d1e")
        (darker-purple   "#462929")

        (dark-red        "#be241e")
        (dark-orange     "#ac4003")
        (dark-yellow     "#a57109")
        (dark-olive      "#746f06")
        (dark-green      "#24601c")
        (dark-cyan       "#2b5434")
        (dark-purple     "#a63445")

        (red             "#e83437")
        (orange          "#d6580e")
        (yellow          "#d09420")
        (olive           "#98952a")
        (green           "#3f9f32")
        (cyan            "#689e69")
        (purple          "#b16262")

        (light-red       "#fc5356")
        (light-orange    "#fc823c")
        (light-yellow    "#fac240")
        (light-olive     "#b5ba25")
        (light-green     "#5ac04e")
        (light-cyan      "#8ec07c")
        (light-purple    "#ed8585")

        (lighter-red     "#fca39c")
        (lighter-orange  "#fca765")
        (lighter-yellow  "#edd76d")
        (lighter-olive   "#dfe26c")
        (lighter-green   "#a2ea98")
        (lighter-cyan    "#aed8a0")
        (lighter-purple  "#f7b4b4"))
      contrasts)

    (
     ;; Basic faces
     (default             (:background bg :foreground fg))
     (button              (:underline t :weight 'bold :foreground yellow))
     (cursor              (:background fg))
     (mode-line           (:background neutral10 :foreground neutral2 :box (:line-width 1 :color neutral15 :style 'released-button)))
     (mode-line-active    (:inherit 'mode-line))
     (mode-line-inactive  (:inherit 'mode-line))
     (fringe              (:background bg))
     (hl-line             (:background grey0))
     (region              (:background grey5)) ;; selection
     (secondary-selection (:background grey6))
     (minibuffer-prompt   (:background bg :foreground high-green :bold t))
     (vertical-border     (:foreground grey7))
     (internal-border     (:background grey7))
     (window-divider      (:foreground grey8))
     (link                (:foreground high-yellow :underline t))
     (link-visited        (:foreground lighter-purple :inherit 'link))
     (shadow              (:foreground grey8))

     (error               (:foreground red :bold t))
     (success             (:foreground high-olive :bold t))
     (warning             (:foreground high-yellow :bold t))

     (alert-low-face      (:foreground high-cyan))
     (trailing-whitespace (:background red))
     (escape-glyph        (:foreground cyan))
     (header-line         (:background grey5 :foreground grey13 :box nil :inherit nil))
     (highlight           (:background grey4 :foreground fg))
     (homoglyph           (:foreground yellow))
     (match               (:foreground grey0 :background cyan))

     (bold (:weight 'bold))
     (italic (:slant 'italic))
     (bold-italic (:weight 'bold :slant 'italic))
     (underline (:underline t))

     (yeet/mode-line-buffer-name (:background lighter-yellow))
     (yeet/mode-line-readable-buffer   (:foreground darker-red :weight 'bold))
     (yeet/mode-line-writeable-buffer  (:foreground darker-yellow :weight 'bold))
     (yeet/mode-line-executable-buffer (:foreground darker-olive :weight 'bold))
     (yeet/mode-line-shadow (:foreground neutral6))

     ;; Font lock (syntax highlighting)
     (font-lock-builtin-face        (:foreground high-cyan))
     (font-lock-constant-face       (:foreground high-purple :bold nil))
     (font-lock-comment-face        (:foreground grey8))
     (font-lock-function-name-face  (:foreground high-yellow :bold nil))
     (font-lock-keyword-face        (:foreground high-red))
     (font-lock-string-face         (:foreground high-olive))
     (font-lock-variable-name-face  (:foreground high-yellow))
     (font-lock-type-face           (:foreground high-orange))
     (font-lock-warning-face        (:foreground high-red :bold t))
     (font-lock-preprocessor-face   (:foreground high-cyan))
     (font-lock-negation-char-face  (:foreground high-red))
     (font-lock-comment-delimiter-face (:inherit 'font-lock-comment-face))
     (font-lock-doc-face (:inherit 'font-lock-string-face))
     (font-lock-doc-markup-face (:inherit 'font-lock-constant-face))
     (font-lock-regexp-grouping-backslash (:inherit 'bold))
     (font-lock-regexp-grouping-construct (:inherit 'bold))
     (font-lock-misc-punctuation-face (:inherit 'font-lock-punctuation-face))
     (font-lock-delimiter-face (:inherit 'font-lock-punctuation-face))
     (font-lock-bracket-face (:inherit 'font-lock-punctuation-face))
     (font-lock-punctuation-face nil)
     (font-lock-property-use-face (:inherit 'font-lock-property-name-face))
     (font-lock-property-name-face (:inherit 'font-lock-variable-name-face))
     (font-lock-operator-face (:inherit 'font-lock-builtin-face))
     (font-lock-number-face (:inherit 'font-lock-constant-face))
     (font-lock-escape-face (:inherit 'font-lock-regexp-grouping-backslash))
     (font-lock-regexp-face (:inherit 'font-lock-string-face))
     (font-lock-variable-use-face (:inherit 'font-lock-variable-name-face))
     (font-lock-function-call-face (:inherit 'font-lock-function-name-face))

     ;; tuareg
     (tuareg-font-lock-interactive-directive-face (:foreground high-cyan))
     (tuareg-font-lock-operator-face (:foreground grey11))
     (tuareg-font-lock-governing-face (:foreground high-red))
     (tuareg-font-double-semicolon-face (:foreground high-red))
     (tuareg-font-lock-module-face (:foreground high-yellow))

     ;; tree-sitter
     (treesit-explorer-field-name nil)
     (treesit-explorer-anonymous-node (:inherit 'shadow))

     ;; display-line-number
     (line-number               (:foreground grey10 :background bg))
     (line-number-current-line  (:foreground high-orange :background grey3))

     ;; company-mode
     (company-scrollbar-bg                 (:background grey5))
     (company-scrollbar-fg                 (:background bg))
     (company-tooltip                      (:background bg))
     (company-tooltip-annotation           (:foreground high-green))
     (company-tooltip-annotation-selection (:inherit 'company-tooltip-annotation))
     (company-tooltip-selection            (:foreground high-purple :background grey5))
     (company-tooltip-common               (:foreground high-orange :underline t))
     (company-tooltip-common-selection     (:foreground high-orange :underline t))
     (company-tooltip-deprecated (:strike-through t))
     (company-tooltip-search (:inherit 'highlight))
     (company-tooltip-search-selection (:inherit 'highlight))
     (company-tooltip-mouse (:inherit 'highlight))
     (company-tooltip-quick-access (:inherit 'company-tooltip-annotation))
     (company-tooltip-quick-access-selection (:inherit 'company-tooltip-annotation-selection))
     (company-tooltip-scrollbar-thumb (:background bg))
     (company-tooltip-scrollbar-track (:background neutral5))
     (company-preview-common               (:foreground grey13))
     (company-preview                      (:background high-orange))
     (company-preview-search               (:background high-cyan))
     (company-template-field               (:foreground grey0 :background high-yellow))
     (company-echo-common                  (:foreground red))
     (company-echo nil)

     ;; org-mode
     (org-latex-and-related     (:foreground lower-yellow))
     (org-document-title        (:foreground high-purple))
     (org-block-begin-line      (:foreground grey6 :background grey0))
     (org-block-end-line        (:foreground grey6 :background grey0))
     (org-special-keyword       (:foreground grey8))
     (org-document-info         (:foreground orange))
     (org-meta-line             (:foreground grey8))

     (org-level-1  (:foreground high-orange))
     (org-level-2  (:foreground high-olive))
     (org-level-3  (:foreground high-red))
     (org-level-4  (:foreground high-yellow))
     (org-level-5  (:foreground high-cyan))
     (org-level-6  (:foreground high-purple))
     (org-level-7  (:foreground high-green))
     (org-level-8  (:foreground high-orange))

     (org-drawer   (:foreground grey7))
     (org-tag      (:inherit 'org-drawer))
     (org-link     (:underline (:style 'line :color grey5)))
     (org-done     (:foreground high-yellow))
     (org-todo     (:foreground high-yellow))
     (org-table    (:foreground grey12))
     (org-block    (:inherit 'default))
     (org-footnote (:foreground yellow))
     (org-checkbox-statistics-todo (:foreground higher-purple))
     (org-checkbox-statistics-done (:foreground high-cyan))
     (org-default (:inherit 'default))
     (org-hide (:foreground neutral14))
     (org-dispatcher-highlight (:weight 'bold :foreground light-yellow :background neutral3))
     (org-property-value nil)
     (org-column (:weight 'normal :slant 'normal :underline nil :strike-through nil :background neutral5))
     (org-column-title (:weight 'bold :underline t :background neutral5))
     (org-warning (:inherit 'font-lock-warning-face))
     (org-archived (:inherit 'shadow))
     (org-cite (:inherit 'link))
     (org-cite-key (:inherit 'link))
     (org-ellipsis (:underline t :foreground lighter-yellow))
     (org-target (:underline t))
     (org-date (:underline t :foreground lighter-cyan))
     (org-date-selected (:inverse-video t :foreground lighter-purple))
     (org-sexp-date (:foreground lighter-cyan))
     (org-list-dt (:weight 'bold))
     (org-indent (:inherit 'org-hide))
     (org-headline-todo (:foreground lighter-purple))
     (org-headline-done (:foreground lighter-orange))
     (org-priority (:inherit 'font-lock-keyword-face))
     (org-checkbox (:inherit 'bold))
     (org-table-header (:foreground bg :background neutral11 :inherit 'org-table))
     (org-formula (:foreground light-orange))
     (org-code (:inherit 'shadow))
     (org-document-info-keyword (:inherit 'shadow))
     (org-inline-src-block (:inherit 'org-block))
     (org-verbatim (:inherit 'shadow))
     (org-quote (:inherit 'org-block))
     (org-verse (:inherit 'org-block))
     (org-clock-overlay (:foreground neutral15 :background neutral6))
     (org-scheduled (:foreground lighter-green))
     (org-scheduled-today (:foreground lighter-green))
     (org-agenda-dimmed-todo-face (:foreground neutral8))
     (org-scheduled-previously (:foreground light-orange))
     (org-imminent-deadline (:inherit 'org-warning))
     (org-upcoming-deadline (:foreground light-orange))
     (org-upcoming-distant-deadline (:inherit 'org-default))
     (org-time-grid (:foreground lighter-yellow))
     (org-macro (:inherit 'org-latex-and-related))
     (org-tag-group (:inherit 'org-tag))
     (org-mode-line-clock (:inherit 'mode-line))
     (org-mode-line-clock-overrun (:background red :inherit 'mode-line))

     ;; org-agenda
     (org-agenda-column-dateline (:inherit 'org-column))
     (org-agenda-done (:foreground lighter-green))
     (org-agenda-structure (:foreground neutral9))
     (org-agenda-structure-secondary (:inherit 'org-agenda-structure))
     (org-agenda-structure-filter (:inherit ('org-warning 'org-agenda-structure)))
     (org-agenda-date (:inherit 'org-agenda-structure))
     (org-agenda-date-today (:weight 'bold :slant 'italic :inherit 'org-agenda-date))
     (org-agenda-date-weekend-today (:inherit 'org-agenda-date-today))
     (org-agenda-clocking (:inherit 'secondary-selection))
     (org-agenda-date-weekend (:weight 'bold :inherit 'org-agenda-date))
     (org-agenda-current-time (:inherit 'org-time-grid))
     (org-agenda-diary (:inherit 'default))
     (org-agenda-calendar-daterange (:inherit 'default))
     (org-agenda-calendar-event (:inherit 'default))
     (org-agenda-calendar-sexp (:inherit 'default))
     (org-agenda-restriction-lock (:background neutral1))
     (org-agenda-filter-tags (:inherit 'mode-line))
     (org-agenda-filter-category (:inherit 'mode-line))
     (org-agenda-filter-effort (:inherit 'mode-line))
     (org-agenda-filter-regexp (:inherit 'mode-line))

     ;; org-roam
     (org-roam-shielded (:inherit ('warning)))
     (org-roam-header-line (:weight 'bold :extend t :foreground higher-yellow))
     (org-roam-title (:weight 'bold))
     (org-roam-olp (:foreground neutral6))
     (org-roam-preview-heading (:extend t :foreground neutral10 :background neutral4))
     (org-roam-preview-heading-highlight (:extend t :foreground neutral10 :background neutral6))
     (org-roam-preview-heading-selection (:extend t :foreground light-orange :inherit 'org-roam-preview-heading-highlight))
     (org-roam-preview-region (:extend t :inherit 'bold))
     (org-roam-dim (:foreground neutral6))
     (org-roam-dailies-calendar-note (:underline nil :inherit ('org-link)))

     ;; jupyter-repl
     (jupyter-repl-input-prompt  (:foreground olive))
     (jupyter-repl-output-prompt (:foreground red))

     ;; dashboard
     (dashboard-items-face  (:foreground grey13))
     (dashboard-main-button (:foreground grey13 :bold t))

     ;; hi-lock
     (hi-yellow (:foreground bg :background lighter-olive))
     (hi-pink (:foreground bg :background lighter-purple))
     (hi-green (:foreground bg :background lighter-green))
     (hi-blue (:foreground bg :background neutral15))
     (hi-salmon (:foreground bg :background lighter-orange))
     (hi-aquamarine (:foreground bg :background lighter-green))
     (hi-black-b (:weight 'bold))
     (hi-blue-b (:weight 'bold :foreground neutral4))
     (hi-green-b (:weight 'bold :foreground light-green))
     (hi-red-b (:weight 'bold :foreground red))
     (hi-black-hb (:height 1.67 :weight 'bold :inherit 'variable-pitch))

     ;; orderless
     (orderless-match-face-0 (:foreground high-cyan :bold t))
     (orderless-match-face-1 (:foreground high-olive :bold t))
     (orderless-match-face-2 (:foreground high-orange :bold t))
     (orderless-match-face-3 (:foreground high-yellow :bold t))

     ;; rainbow-delimiters
     (rainbow-delimiters-base-face nil)
     (rainbow-delimiters-base-error-face (:foreground darker-red :inherit 'rainbow-delimiters-base-face))
     (rainbow-delimiters-unmatched-face (:foreground high-red))
     (rainbow-delimiters-mismatched-face (:inherit 'rainbow-delimiters-unmatched-face))

     (rainbow-delimiters-depth-1-face   (:foreground higher-cyan))
     (rainbow-delimiters-depth-2-face   (:foreground higher-purple))
     (rainbow-delimiters-depth-3-face   (:foreground higher-green))
     (rainbow-delimiters-depth-4-face   (:foreground higher-orange))
     (rainbow-delimiters-depth-5-face   (:foreground higher-cyan))
     (rainbow-delimiters-depth-6-face   (:foreground higher-purple))
     (rainbow-delimiters-depth-7-face   (:foreground higher-green))
     (rainbow-delimiters-depth-8-face   (:foreground higher-orange))
     (rainbow-delimiters-depth-9-face   (:foreground higher-cyan))
     (rainbow-delimiters-depth-10-face  (:foreground higher-purple))
     (rainbow-delimiters-depth-11-face  (:foreground higher-green))
     (rainbow-delimiters-depth-12-face  (:foreground higher-orange))

     ;; eshell
     (eshell-prompt        (:foreground cyan))
     (eshell-ls-archive    (:foreground grey7))
     (eshell-ls-backup     (:foreground grey7))
     (eshell-ls-clutter    (:foreground orange :bold t))
     (eshell-ls-directory  (:foreground yellow))
     (eshell-ls-executable (:bold t))
     (eshell-ls-missing    (:foreground high-red :bold t))
     (eshell-ls-product    (:foreground low-red))
     (eshell-ls-readonly   (:foreground grey7))
     (eshell-ls-special    (:foreground high-yellow :bold t))
     (eshell-ls-symlink    (:foreground high-red))
     (eshell-ls-unreadable (:foreground high-red :bold t))

     ;; lsp
     (lsp-face-highlight-textual        (:background grey6))
     (lsp-face-highlight-read           (:background grey6))
     (lsp-face-highlight-write          (:background grey6))
     (lsp-face-semhl-constant           (:foreground cyan))
     (lsp-face-semhl-deprecated         (:foreground cyan))
     (lsp-face-semhl-enummember         (:foreground cyan))
     (lsp-face-semhl-field              (:foreground cyan))
     (lsp-face-semhl-field-static       (:foreground cyan))
     (lsp-face-semhl-function           (:foreground cyan))
     (lsp-face-semhl-method             (:foreground cyan))
     (lsp-face-semhl-namespace          (:foreground cyan))
     (lsp-face-semhl-preprocessor       (:foreground cyan))
     (lsp-face-semhl-static-method      (:foreground cyan))
     (lsp-face-semhl-type-class         (:foreground cyan))
     (lsp-face-semhl-type-enum          (:foreground cyan))
     (lsp-face-semhl-type-primitive     (:foreground cyan))
     (lsp-face-semhl-type-template      (:foreground cyan))
     (lsp-face-semhl-type-typedef       (:foreground cyan))
     (lsp-face-semhl-variable           (:foreground cyan))
     (lsp-face-semhl-variable-local     (:foreground cyan))
     (lsp-face-semhl-variable-parameter (:foreground cyan))
     (lsp-lens-face                     (:foreground cyan))
     (lsp-lens-mouse-face               (:foreground cyan))
     (lsp-ui-doc-background             (:foreground cyan))
     (lsp-ui-doc-header                 (:foreground cyan))
     (lsp-ui-doc-url                    (:foreground cyan))
     (lsp-ui-peek-filename              (:foreground cyan))
     (lsp-ui-peek-footer                (:foreground cyan))
     (lsp-ui-peek-header                (:foreground cyan))
     (lsp-ui-peek-highlight             (:foreground cyan))
     (lsp-ui-peek-line-number           (:foreground cyan))
     (lsp-ui-peek-list                  (:foreground cyan))
     (lsp-ui-peek-peek                  (:foreground cyan))
     (lsp-ui-peek-selection             (:foreground cyan))
     (lsp-ui-sideline-code-action       (:foreground cyan))
     (lsp-ui-sideline-current-symbol    (:foreground cyan))
     (lsp-ui-sideline-symbol            (:foreground cyan))
     (lsp-ui-sideline-symbol-info       (:foreground cyan))

     ;; flymake
     (flymake-end-of-line-diagnostics-face (:height 0.85 :box (:line-width -1)))

     (flymake-error (:underline (:style 'wave :color high-red)))
     (flymake-error-echo (:inherit 'compilation-error))
     (flymake-error-echo-at-eol (:inherit ('flymake-end-of-line-diagnostics-face 'compilation-error)))

     (flymake-warning (:underline (:style 'wave :color high-cyan)))
     (flymake-warning-echo (:inherit 'compilation-warning))
     (flymake-warning-echo-at-eol (:inherit ('flymake-end-of-line-diagnostics-face 'compilation-warning)))

     (flymake-note (:underline (:style 'wave :color high-olive)))
     (flymake-note-echo (:inherit 'flymake-note))
     (flymake-note-echo-at-eol (:inherit ('flymake-end-of-line-diagnostics-face 'flymake-note)))

     ;; flyspell
     (flyspell-incorrect (:underline (:style 'wave :color red)))

     ;; git-gutter
     (git-gutter:added (:foreground higher-green :weight 'bold))
     (git-gutter:modified (:foreground higher-purple :weight 'bold))
     (git-gutter:deleted (:foreground higher-red :weight 'bold))
     (git-gutter:separator (:weight 'bold :foreground lighter-cyan :inherit 'default))
     (git-gutter:unchanged (:background lighter-olive :inherit 'default))

     ;; whitespace
     (whitespace-tab      (:background bg :foreground grey6))
     (whitespace-space    (:background bg :foreground grey6))
     (whitespace-hspace   (:background bg :foreground grey6))
     (whitespace-newline  (:background bg :foreground grey6))
     (whitespace-line     (:background bg :foreground grey6))
     (whitespace-empty    (:background bg :foreground grey6))
     (whitespace-indentation      (:background bg :foreground grey6))
     (whitespace-big-indent       (:background bg :foreground grey6))
     (whitespace-space-after-tab  (:background bg :foreground grey6))
     (whitespace-space-before-tab       (:background high-red))
     (whitespace-missing-newline-at-eof (:background high-red))
     (whitespace-trailing               (:background high-red))

     ;; diff
     (diff-header      (:extend t :background grey3))
     (diff-hunk-header (:inherit 'diff-header))
     (diff-file-header (:weight 'bold :extend t :background grey4))
     (diff-changed nil)
     (diff-removed (:extend t :background lower-red   :inherit 'diff-changed))
     (diff-added   (:extend t :background lower-green :inherit 'diff-changed))
     (diff-refine-changed nil)
     (diff-refine-removed (:background low-red   :inherit 'diff-refine-changed))
     (diff-refine-added   (:background low-green :inherit 'diff-refine-changed))

     (diff-index (:inherit 'diff-file-header))
     (diff-changed-unspecified (:extend t :background neutral3 :inherit 'diff-changed))
     (diff-indicator-removed (:foreground dark-red :inherit 'diff-removed))
     (diff-indicator-added (:foreground green :inherit 'diff-added))
     (diff-indicator-changed (:foreground light-olive :inherit 'diff-changed))
     (diff-function (:inherit 'diff-header))
     (diff-context (:extend t))
     (diff-nonexistent (:inherit 'diff-file-header))
     (diff-error (:weight 'bold :foreground red :background bg))

     ;; mini-modeline
     (mini-modeline-mode-line  (:background low-olive :height 0.14 :box nil))

     ;; dired
     (dired-broken-symlink (:foreground grey1 :background red :bold t))
     (dired-symlink (:foreground cyan))
     (dired-directory (:foreground orange))
     (dired-header (:inherit 'font-lock-type-face))
     (dired-mark (:inherit 'font-lock-constant-face))
     (dired-marked (:inherit 'warning))
     (dired-flagged (:inherit 'error))
     (dired-warning (:inherit 'font-lock-warning-face))
     (dired-perm-write (:inherit 'font-lock-comment-delimiter-face))
     (dired-set-id (:inherit 'font-lock-warning-face))
     (dired-special (:inherit 'font-lock-variable-name-face))
     (dired-ignored (:inherit 'shadow))

     ;; isearch
     (isearch (:foreground grey13 :background lower-purple))
     (isearch-fail (:foreground grey13 :background lower-red))
     (isearch-group-1 (:foreground high-red :background low-purple))
     (isearch-group-2 (:foreground high-red :background low-purple))
     (lazy-highlight (:background grey4))

     (query-replace (:inherit 'isearch))

     ;; meow
     (meow-normal-indicator (:foreground darker-olive))
     (meow-insert-indicator (:foreground darker-red))
     (meow-beacon-indicator (:foreground darker-cyan))
     (meow-keypad-indicator (:foreground darker-purple))
     (meow-motion-indicator (:foreground darker-green))
     (meow-search-indicator (:foreground darker-yellow))

     (meow-normal-cursor (:background high-orange))
     (meow-insert-cursor (:background high-yellow))
     (meow-beacon-cursor (:background high-cyan))
     (meow-keypad-cursor (:background high-red))
     (meow-motion-cursor (:background high-green))
     (meow-beacon-fake-cursor (:extend nil :foreground bg :background purple :inherit 'region))
     (meow-unknown-cursor (:inherit 'cursor))
     (meow-region-cursor-1 (:foreground neutral12 :background olive))
     (meow-region-cursor-2 (:foreground neutral12 :background neutral8))
     (meow-region-cursor-3 (:foreground neutral12 :background neutral6))
     (meow-kmacro-cursor (:underline t))

     (meow-keypad-cannot-display  (:height 0.7 :foreground neutral15))
     (meow-beacon-fake-selection (:foreground bg :background neutral5 :inherit 'region))
     (meow-search-highlight (:inherit 'lazy-highlight))
     (meow-position-highlight-number (:foreground bg :inherit 'default))
     (meow-position-highlight-number-1 (:background purple :inherit 'meow-position-highlight-number))
     (meow-position-highlight-number-2 (:background neutral6 :inherit 'meow-position-highlight-number))
     (meow-position-highlight-number-3 (:background neutral5 :inherit 'meow-position-highlight-number))
     (meow-position-highlight-reverse-number-1 (:inherit 'meow-position-highlight-number-1))
     (meow-position-highlight-reverse-number-2 (:inherit 'meow-position-highlight-number-2))
     (meow-position-highlight-reverse-number-3 (:inherit 'meow-position-highlight-number-3))
     (meow-cheatsheet-command (:height 90 :inherit 'fixed-pitch))
     (meow-cheatsheet-highlight (:foreground neutral15 :inherit 'meow-cheatsheet-command))

     ;; vterm
     (vterm-color-cyan    (:foreground cyan))
     (vterm-color-green   (:foreground olive))
     (vterm-color-black   (:foreground grey2))
     (vterm-color-blue    (:foreground orange))
     (vterm-color-red     (:foreground red))
     (vterm-color-yellow  (:foreground yellow))
     (vterm-color-white   (:foreground grey11))
     (vterm-color-magenta (:foreground purple))

     ;; eglot
     (eglot-highlight-symbol-face (:inherit 'bold))
     (eglot-mode-line (:foreground dark-purple :weight 'bold :inherit 'font-lock-constant-face))
     (eglot-diagnostic-tag-unnecessary-face (:inherit 'shadow))
     (eglot-diagnostic-tag-deprecated-face (:strike-through t :inherit 'shadow))
     (eglot-inlay-hint-face (:inherit 'shadow))
     (eglot-type-hint-face (:inherit 'eglot-inlay-hint-face))
     (eglot-parameter-hint-face (:inherit 'eglot-inlay-hint-face))

     ;; realgud
     (realgud-debugger-running     (:weight 'bold :foreground high-green))
     (realgud-debugger-not-running (:inherit 'font-lock-warning-face))
     (realgud-overlay-arrow1       (:inherit 'realgud-debugger-running))
     (realgud-overlay-arrow2       (:weight 'bold :foreground grey15))
     (realgud-overlay-arrow3       (:foreground grey6))
     (realgud-bp-enabled-face       (:weight 'bold :foreground high-red))
     (realgud-bp-line-enabled-face  (:box (:color high-red)))
     (realgud-bp-disabled-face      (:weight 'bold :foreground grey10))
     (realgud-bp-line-disabled-face (:box (:color grey10)))
     (realgud-line-numbers (:inherit 'font-lock-variable-name-face))
     (realgud-file-name (:inherit 'font-lock-preprocessor-face))
     (realgud-backtrace-number (:weight 'bold :foreground bg))

     (debugger-running             (:weight 'bold :foreground high-green))
     (debugger-not-running (:inherit 'font-lock-warning-face))

     ;; ansi-color
     (ansi-color-black   (:foreground bg :background bg))
     (ansi-color-red     (:foreground red    :background red))
     (ansi-color-green   (:foreground olive  :background olive))
     (ansi-color-yellow  (:foreground yellow :background yellow))
     (ansi-color-blue    (:foreground orange :background orange))
     (ansi-color-magenta (:foreground purple :background purple))
     (ansi-color-cyan    (:foreground cyan   :background cyan))
     (ansi-color-white   (:foreground neutral15 :background neutral15))

     (ansi-color-bright-black   (:foreground neutral5 :background neutral5))
     (ansi-color-bright-red     (:foreground light-red    :background light-red))
     (ansi-color-bright-green   (:foreground light-olive  :background light-olive))
     (ansi-color-bright-yellow  (:foreground light-yellow :background light-yellow))
     (ansi-color-bright-blue    (:foreground light-orange :background light-orange))
     (ansi-color-bright-magenta (:foreground light-purple :background light-purple))
     (ansi-color-bright-cyan    (:foreground light-cyan   :background light-cyan))
     (ansi-color-bright-white   (:foreground neutral15 :background neutral15))

     (ansi-color-bold (:inherit ('quote 'bold)))
     (ansi-color-faint (:weight 'light))
     (ansi-color-italic (:inherit ('quote 'italic)))
     (ansi-color-underline (:inherit ('quote 'underline)))
     (ansi-color-slow-blink (:box (:line-width -1)))
     (ansi-color-fast-blink (:box (:line-width -1)))
     (ansi-color-inverse (:inverse-video t))

     ;; message
     (message-header-other (:foreground orange))
     (message-header-to (:weight 'bold :foreground fg))
     (message-header-subject (:foreground fg))
     (message-header-name (:foreground light-yellow))

     ;; sh
     (sh-heredoc (:foreground high-olive))
     (sh-quoted-exec (:foreground light-purple))
     (sh-escaped-newline (:inherit 'font-lock-string-face))

     ;; j-mode
     (j-verb-face (:inherit 'font-lock-builtin-face))
     (j-adverb-face (:inherit 'font-lock-builtin-face))
     (j-conjunction-face (:inherit 'font-lock-builtin-face))
     (j-other-face (:inherit 'default))

     ;; custom
     (custom-invalid (:foreground lighter-olive :background red))
     (custom-rogue (:foreground lighter-purple :background neutral0))
     (custom-modified (:foreground neutral15 :background neutral4))
     (custom-set (:foreground neutral4 :background neutral15))
     (custom-changed (:foreground neutral15 :background neutral4))
     (custom-themed (:foreground neutral15 :background neutral4))
     (custom-saved (:underline t))
     (custom-button (:box (:line-width 2 :style 'released-button) :foreground neutral0 :background neutral11))
     (custom-button-mouse (:box (:line-width 2 :style 'released-button) :foreground neutral0 :background neutral15))
     (custom-button-unraised (:inherit 'underline))
     (custom-button-pressed (:box (:line-width 2 :style 'pressed-button) :foreground neutral0 :background neutral11))
     (custom-button-pressed-unraised (:foreground dark-purple :inherit 'custom-button-unraised))
     (custom-documentation nil)
     (custom-state (:foreground dark-green))
     (custom-link (:inherit 'link))
     (custom-comment (:background neutral15))
     (custom-comment-tag (:foreground neutral1))
     (custom-variable-obsolete (:foreground neutral4))
     (custom-variable-tag (:weight 'bold :foreground neutral4))
     (custom-variable-button (:weight 'bold :underline t))
     (custom-visibility (:height 0.8 :inherit 'link))
     (custom-face-tag (:inherit 'custom-variable-tag))
     (custom-group-tag-1 (:height 1.2 :weight 'bold :foreground red :inherit 'variable-pitch))
     (custom-group-tag (:height 1.2 :weight 'bold :foreground neutral4 :inherit 'variable-pitch))
     (custom-group-subtitle (:weight 'bold))

     ;; which-key
     (which-key-key-face (:inherit 'font-lock-constant-face))
     (which-key-separator-face (:inherit 'font-lock-comment-face))
     (which-key-note-face (:inherit 'which-key-separator-face))
     (which-key-command-description-face (:inherit 'font-lock-function-name-face))
     (which-key-local-map-description-face (:inherit 'which-key-command-description-face))
     (which-key-highlighted-command-face (:underline t :inherit 'which-key-command-description-face))
     (which-key-group-description-face (:inherit 'font-lock-keyword-face))
     (which-key-special-key-face (:weight 'bold :inverse-video t :inherit 'which-key-key-face))
     (which-key-docstring-face (:inherit 'which-key-note-face))

     ;; elpaca
     (elpaca-finished (:weight 'bold :foreground green))
     (elpaca-busy     (:weight 'bold :foreground yellow))
     (elpaca-blocked  (:weight 'bold :foreground purple))
     (elpaca-failed   (:weight 'bold :foreground red))

     (elpaca-ui-marked-delete  (:weight 'bold :foreground red))
     (elpaca-ui-marked-install (:weight 'bold :foreground neutral4))
     (elpaca-ui-marked-rebuild (:weight 'bold :foreground dark-purple))
     (elpaca-ui-marked-fetch   (:weight 'bold :foreground dark-red))
     (elpaca-ui-marked-update  (:weight 'bold :foreground light-orange))

     (elpaca-log-highlight (:inherit 'warning))
     (elpaca-log-error     (:inherit 'error))
     (elpaca-log-info      (:inherit 'shadow))

     (elpaca-info-section (:weight 'bold))
     (elpaca-info-package (:height 2.0))

     ;; vertico
     (vertico-multiline (:inherit 'shadow))
     (vertico-group-title (:slant 'italic :inherit 'shadow))
     (vertico-group-separator (:strike-through t :inherit 'shadow))
     (vertico-current (:extend t :inherit 'highlight))

     ;; compilation
     (compilation-error (:inherit 'error))
     (compilation-warning (:inherit 'warning))
     (compilation-info (:inherit 'success))
     (compilation-mode-line-fail (:weight 'bold :foreground red :inherit 'compilation-error))
     (compilation-mode-line-run (:inherit 'compilation-warning))
     (compilation-mode-line-exit (:weight 'bold :foreground green :inherit 'compilation-info))
     (compilation-line-number (:inherit 'font-lock-keyword-face))
     (compilation-column-number (:inherit 'font-lock-doc-face))

     ;; magit
     (magit-section-highlight (:extend t :background grey1))
     (magit-section-heading (:weight 'bold :extend t :foreground lighter-yellow))
     (magit-section-secondary-heading (:weight 'bold :extend t))
     (magit-section-heading-selection (:extend t :foreground light-orange))
     (magit-section-child-count nil)

     ;; message
     (message-header-cc (:weight 'bold :foreground lighter-green))
     (message-header-newsgroups (:weight 'bold :slant 'italic :foreground lighter-olive))
     (message-header-xheader (:foreground neutral9))
     (message-separator (:foreground neutral15))
     (message-cited-text-1 (:foreground lighter-purple))
     (message-cited-text-2 (:foreground green))
     (message-cited-text-3 (:foreground yellow))
     (message-cited-text-4 (:foreground orange))
     (message-mml (:foreground lighter-green))
     (message-signature-separator (:weight 'bold))

     ;; vc
     (vc-state-base nil)
     (vc-up-to-date-state (:inherit 'vc-state-base))
     (vc-needs-update-state (:inherit 'vc-state-base))
     (vc-locked-state (:inherit 'vc-state-base))
     (vc-locally-added-state (:inherit 'vc-state-base))
     (vc-conflict-state (:inherit 'vc-state-base))
     (vc-removed-state (:inherit 'vc-state-base))
     (vc-missing-state (:inherit 'vc-state-base))
     (vc-edited-state (:inherit 'vc-state-base))

     ;; eww
     (eww-form-submit (:box (:line-width 2 :style 'released-button) :foreground bg :background neutral8))
     (eww-form-file (:box (:line-width 2 :style 'released-button) :foreground bg :background neutral8))
     (eww-form-checkbox (:box (:line-width 2 :style 'released-button) :foreground bg :background neutral11))
     (eww-form-select (:box (:line-width 2 :style 'released-button) :foreground bg :background neutral11))
     (eww-form-text (:box (:line-width 1) :foreground neutral15 :background neutral5))
     (eww-form-textarea (:box (:line-width 1) :foreground bg :background neutral11))
     (eww-invalid-certificate (:weight 'bold :foreground red))
     (eww-valid-certificate (:weight 'bold :foreground green))

     ;; rst
     (rst-block (:inherit 'font-lock-keyword-face))
     (rst-external (:inherit 'font-lock-type-face))
     (rst-definition (:inherit 'font-lock-function-name-face))
     (rst-directive (:inherit 'font-lock-builtin-face))
     (rst-comment (:inherit 'font-lock-comment-face))
     (rst-emphasis1 (:inherit 'italic))
     (rst-emphasis2 (:inherit 'bold))
     (rst-literal (:inherit 'font-lock-string-face))
     (rst-reference (:inherit 'font-lock-variable-name-face))
     (rst-transition (:inherit 'font-lock-keyword-face))
     (rst-adornment (:inherit 'font-lock-keyword-face))
     (rst-level-1 (:background neutral2))
     (rst-level-2 (:background neutral3))
     (rst-level-3 (:background neutral5))
     (rst-level-4 (:background neutral6))
     (rst-level-5 (:background neutral7))
     (rst-level-6 (:background neutral8))

     ;; gnus
     (gnus-group-news-1-empty (:foreground lighter-cyan))
     (gnus-group-news-1 (:weight 'bold :inherit 'gnus-group-news-1-empty))
     (gnus-group-news-2-empty (:foreground lighter-cyan))
     (gnus-group-news-2 (:weight 'bold :inherit 'gnus-group-news-2-empty))
     (gnus-group-news-3-empty nil)
     (gnus-group-news-3 (:weight 'bold :inherit 'gnus-group-news-3-empty))
     (gnus-group-news-4-empty nil)
     (gnus-group-news-4 (:weight 'bold :inherit 'gnus-group-news-4-empty))
     (gnus-group-news-5-empty nil)
     (gnus-group-news-5 (:weight 'bold :inherit 'gnus-group-news-5-empty))
     (gnus-group-news-6-empty nil)
     (gnus-group-news-6 (:weight 'bold :inherit 'gnus-group-news-6-empty))
     (gnus-group-news-low-empty (:foreground lighter-cyan))
     (gnus-group-news-low (:weight 'bold :inherit 'gnus-group-news-low-empty))
     (gnus-group-mail-1-empty (:foreground lighter-cyan))
     (gnus-group-mail-1 (:weight 'bold :inherit 'gnus-group-mail-1-empty))
     (gnus-group-mail-2-empty (:foreground lighter-green))
     (gnus-group-mail-2 (:weight 'bold :inherit 'gnus-group-mail-2-empty))
     (gnus-group-mail-3-empty (:foreground lighter-green))
     (gnus-group-mail-3 (:weight 'bold :inherit 'gnus-group-mail-3-empty))
     (gnus-group-mail-low-empty (:foreground lighter-green))
     (gnus-group-mail-low (:weight 'bold :inherit 'gnus-group-mail-low-empty))
     (gnus-summary-selected (:underline t :extend t))
     (gnus-summary-cancelled (:extend t :foreground lighter-olive :background bg))
     (gnus-summary-normal-ticked (:extend t :foreground lighter-purple))
     (gnus-summary-high-ticked (:weight 'bold :inherit 'gnus-summary-normal-ticked))
     (gnus-summary-low-ticked (:slant 'italic :inherit 'gnus-summary-normal-ticked))
     (gnus-summary-normal-ancient (:extend t :foreground neutral11))
     (gnus-summary-high-ancient (:weight 'bold :inherit 'gnus-summary-normal-ancient))
     (gnus-summary-low-ancient (:slant 'italic :inherit 'gnus-summary-normal-ancient))
     (gnus-summary-normal-undownloaded (:weight 'normal :extend t :foreground cyan))
     (gnus-summary-high-undownloaded (:weight 'bold :inherit 'gnus-summary-normal-undownloaded))
     (gnus-summary-low-undownloaded (:slant 'italic :inherit 'gnus-summary-normal-undownloaded))
     (gnus-summary-normal-unread (:extend t))
     (gnus-summary-high-unread (:weight 'bold :inherit 'gnus-summary-normal-unread))
     (gnus-summary-low-unread (:slant 'italic :inherit 'gnus-summary-normal-unread))
     (gnus-summary-normal-read (:extend t :foreground lighter-green))
     (gnus-summary-high-read (:weight 'bold :inherit 'gnus-summary-normal-read))
     (gnus-summary-low-read (:slant 'italic :inherit 'gnus-summary-normal-read))
     (gnus-splash (:foreground neutral11))
     (gnus-emphasis-bold (:weight 'bold))
     (gnus-emphasis-italic (:slant 'italic))
     (gnus-emphasis-underline (:underline t))
     (gnus-emphasis-underline-bold (:weight 'bold :underline t))
     (gnus-emphasis-underline-italic (:slant 'italic :underline t))
     (gnus-emphasis-bold-italic (:weight 'bold :slant 'italic))
     (gnus-emphasis-underline-bold-italic (:weight 'bold :slant 'italic :underline t))
     (gnus-emphasis-strikethru (:strike-through t))
     (gnus-emphasis-highlight-words (:foreground lighter-olive :background bg))
     (gnus-button (:weight 'bold))
     (gnus-signature (:slant 'italic))
     (gnus-header-from (:foreground lighter-green))
     (gnus-header-subject (:foreground lighter-green))
     (gnus-header-newsgroups (:slant 'italic :foreground lighter-olive))
     (gnus-header-name (:foreground lighter-green))
     (gnus-header-content (:slant 'italic :foreground lighter-green))

     (line-number-major-tick (:weight 'bold :background neutral11))
     (line-number-minor-tick (:weight 'bold :background neutral8))

     (fill-column-indicator (:weight 'normal :slant 'normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :inherit 'shadow))

     (nobreak-space (:underline t :inherit 'escape-glyph))
     (nobreak-hyphen (:foreground lighter-cyan))

     (mode-line-highlight (:box (:line-width 2 :color neutral6 :style 'released-button)))
     (mode-line-emphasis (:weight 'bold))
     (mode-line-buffer-id (:weight 'bold))

     (csv-separator-face (:foreground high-cyan))

     ;; tty-menu
     (tty-menu-enabled-face (:weight 'bold :foreground lighter-olive :background neutral4))
     (tty-menu-disabled-face (:foreground neutral11 :background neutral4))
     (tty-menu-selected-face (:background red))

     ;; show-paren
     (show-paren-match-expression (:inherit 'show-paren-match))
     (show-paren-mismatch (:foreground bg :background high-purple))
     (show-paren-match    (:background low-cyan))

     ;; completions
     (completions-group-title (:slant 'italic :inherit 'shadow))
     (completions-group-separator (:strike-through t :inherit 'shadow))
     (completions-annotations (:inherit ('italic 'shadow)))
     (completions-first-difference (:inherit 'bold))
     (completions-common-part (:foreground neutral15))

     ;; tab-bar
     (tab-bar-tab (:box (:line-width 1 :style 'released-button) :inherit 'tab-bar))
     (tab-bar-tab-inactive (:background neutral11 :inherit 'tab-bar-tab))
     (tab-bar-tab-group-current (:weight 'bold :box nil :inherit 'tab-bar-tab))
     (tab-bar-tab-group-inactive (:inherit ('shadow 'tab-bar-tab-inactive)))
     (tab-bar-tab-ungrouped (:inherit ('shadow 'tab-bar-tab-inactive)))
     (tab-bar (:foreground bg :background neutral15 :inherit 'variable-pitch))

     ;; calendar
     (calendar-today (:underline t))
     (calendar-weekday-header (:inherit 'font-lock-constant-face))
     (calendar-weekend-header (:inherit 'font-lock-comment-face))
     (calendar-month-header (:inherit 'font-lock-function-name-face))

     ;; yas
     (yas-field-highlight-face (:inherit 'region))
     (yas--field-debug-face nil)

     ;; hl-todo
     (hl-todo (:weight 'bold :foreground light-purple))

     ;; xref
     (xref-file-header (:inherit 'compilation-info))
     (xref-line-number (:inherit 'compilation-line-number))
     (xref-match (:inherit 'match))

     ;; outline
     (outline-1 (:inherit 'font-lock-function-name-face))
     (outline-2 (:inherit 'font-lock-variable-name-face))
     (outline-3 (:inherit 'font-lock-keyword-face))
     (outline-4 (:inherit 'font-lock-comment-face))
     (outline-5 (:inherit 'font-lock-type-face))
     (outline-6 (:inherit 'font-lock-constant-face))
     (outline-7 (:inherit 'font-lock-builtin-face))
     (outline-8 (:inherit 'font-lock-string-face))

     ;; widget
     (widget-documentation (:foreground light-green))
     (widget-button (:weight 'bold))
     (widget-field (:extend t :background grey3))
     (widget-single-line-field (:background neutral6))
     (widget-inactive (:inherit 'shadow))
     (widget-button-pressed (:foreground red))

     ;; epa
     (epa-validity-high (:weight 'bold :foreground lighter-cyan))
     (epa-validity-medium (:slant 'italic :foreground lighter-cyan))
     (epa-validity-low (:slant 'italic))
     (epa-validity-disabled (:slant 'italic :inverse-video t))
     (epa-string (:foreground neutral15))
     (epa-mark (:weight 'bold :foreground yellow))
     (epa-field-name (:weight 'bold :foreground lighter-cyan))
     (epa-field-body (:slant 'italic :foreground lighter-cyan))

     ;; shr
     (shr-strike-through (:strike-through t))
     (shr-link (:inherit 'link))
     (shr-selected-link (:background red :inherit 'shr-link))
     (shr-abbreviation (:underline (:style 'wave) :inherit 'underline))
     (shr-h1 (:height 1.3 :weight 'bold))
     (shr-h2 (:weight 'bold))
     (shr-h3 (:slant 'italic))
     (shr-h4 nil)
     (shr-h5 nil)
     (shr-h6 nil)

     ;; speedbar
     (speedbar-button-face (:foreground light-green))
     (speedbar-file-face (:foreground lighter-cyan))
     (speedbar-directory-face (:foreground neutral15))
     (speedbar-tag-face (:foreground lighter-olive))
     (speedbar-selected-face (:underline t :foreground red))
     (speedbar-highlight-face (:background cyan))
     (speedbar-separator-face (:overline neutral10 :foreground neutral15 :background neutral4))

     ;; shortdoc
     (shortdoc-heading (:height 1.3 :weight 'bold :inherit 'variable-pitch))
     (shortdoc-section (:inherit 'variable-pitch))

     ;; window-divider
     (window-divider-first-pixel (:foreground neutral11))
     (window-divider-last-pixel (:foreground neutral6))

     ;; fonts
     (fixed-pitch (:family "SauceCodePro Nerd Font Mono" :height 100 :inherit 'default))
     (fixed-pitch-serif (:family "Monospace Serif"))
     (variable-pitch (:family "NotoSans Display Nerd Font" :height 105))

     ;; nushell
     (nushell-pay-attention-face (:inherit 'font-lock-builtin-face))

     ;; focus
     (focus-unfocused (:inherit 'shadow))
     (focus-focused nil)

     ;; term
     (term (:inherit 'default))
     (term-bold (:inherit 'ansi-color-bold))
     (term-underline (:inherit 'ansi-color-underline))

     (term-color-black   (:inherit 'ansi-color-black))
     (term-color-red     (:inherit 'ansi-color-red))
     (term-color-green   (:inherit 'ansi-color-green))
     (term-color-yellow  (:inherit 'ansi-color-yellow))
     (term-color-blue    (:inherit 'ansi-color-blue))
     (term-color-magenta (:inherit 'ansi-color-magenta))
     (term-color-cyan    (:inherit 'ansi-color-cyan))
     (term-color-white   (:inherit 'ansi-color-white))

     (term-color-bright-black   (:inherit 'ansi-color-bright-black))
     (term-color-bright-red     (:inherit 'ansi-color-bright-red))
     (term-color-bright-green   (:inherit 'ansi-color-bright-green))
     (term-color-bright-yellow  (:inherit 'ansi-color-bright-yellow))
     (term-color-bright-blue    (:inherit 'ansi-color-bright-blue))
     (term-color-bright-magenta (:inherit 'ansi-color-bright-magenta))
     (term-color-bright-cyan    (:inherit 'ansi-color-bright-cyan))
     (term-color-bright-white   (:inherit 'ansi-color-bright-white))

     ;; apropos
     (apropos-symbol (:inherit 'bold))
     (apropos-keybinding (:inherit 'underline))
     (apropos-property (:inherit 'font-lock-builtin-face))
     (apropos-button (:inherit ('font-lock-variable-name-face 'button)))
     (apropos-function-button (:inherit ('font-lock-function-name-face 'button)))
     (apropos-variable-button (:inherit ('font-lock-variable-name-face 'button)))
     (apropos-user-option-button (:inherit ('font-lock-variable-name-face 'button)))
     (apropos-misc-button (:inherit ('font-lock-constant-face 'button)))

     ;; sly
     (sly-action-face (:inherit 'warning))
     (sly-part-button-face (:inherit 'font-lock-constant-face))
     (sly-error-face (:underline light-red))
     (sly-warning-face (:underline (:color high-orange)))
     (sly-style-warning-face (:underline lighter-yellow))
     (sly-note-face (:underline lighter-yellow))
     (sly-db-topline-face nil)
     (sly-db-condition-face (:inherit 'error))
     (sly-db-section-face (:inherit 'header-line))
     (sly-db-frame-label-face (:inherit 'shadow))
     (sly-db-restart-face nil)
     (sly-db-restart-number-face (:inherit 'shadow))
     (sly-db-frame-line-face nil)
     (sly-db-restartable-frame-line-face (:inherit 'font-lock-constant-face))
     (sly-db-non-restartable-frame-line-face nil)
     (sly-db-local-name-face nil)
     (sly-db-catch-tag-face nil)
     (sly-mode-line (:weight 'bold :inherit 'font-lock-constant-face))
     (sly-apropos-symbol (:inherit 'sly-part-button-face))
     (sly-apropos-label (:inherit 'italic))
     (sly-mrepl-prompt-face (:inherit 'font-lock-builtin-face))
     (sly-mrepl-note-face (:inherit 'font-lock-keyword-face))
     (sly-mrepl-output-face (:foreground fg))
     (sly-reader-conditional-face (:inherit 'font-lock-comment-face))
     (sly-stickers-placed-face (:foreground bg :background neutral11))
     (sly-stickers-armed-face (:strike-through nil :inherit 'hi-blue))
     (sly-stickers-recordings-face (:strike-through nil :inherit 'hi-green))
     (sly-stickers-empty-face (:strike-through nil :inherit 'hi-pink))
     (sly-stickers-exited-non-locally-face (:strike-through t :inherit 'sly-stickers-empty-face))

     ;; info
     (info-node (:weight 'bold :slant 'italic :foreground neutral15))
     (info-title-1 (:height 1.2 :inherit 'info-title-2))
     (info-title-2 (:height 1.2 :inherit 'info-title-3))
     (info-title-3 (:height 1.2 :inherit 'info-title-4))
     (info-title-4 (:weight 'bold :inherit 'variable-pitch))
     (info-menu-header (:weight 'bold :inherit 'variable-pitch))
     (info-menu-star (:foreground red))
     (info-xref (:inherit 'link))
     (info-xref-visited (:inherit ('link-visited 'info-xref)))
     (info-header-xref (:inherit 'info-xref))
     (info-header-node (:inherit 'info-node))
     (info-index-match (:inherit 'match))

     ;; ess
     (ess-watch-current-block-face (:inherit 'highlight))
     (ess-bp-fringe-recover-face (:foreground dark-purple))
     (ess-bp-fringe-browser-face (:foreground neutral3))
     (ess-bp-fringe-logger-face (:foreground darker-red))
     (ess-bp-fringe-inactive-face (:foreground neutral6))
     (ess-debug-blink-same-ref-face (:background neutral7))
     (ess-debug-blink-ref-not-found-face (:background dark-purple))
     (ess-debug-current-debug-line-face (:inherit 'highlight))
     (ess-tracebug-last-input-fringe-face (:overline neutral3 :foreground neutral3))
     (ess-r-control-flow-keyword-face (:inherit 'ess-keyword-face))
     (ess-keyword-face (:inherit 'font-lock-keyword-face))
     (ess-matrix-face (:inherit 'font-lock-constant-face))
     (ess-constant-face (:inherit 'font-lock-type-face))
     (ess-modifiers-face (:inherit 'font-lock-constant-face))
     (ess-paren-face (:inherit 'font-lock-constant-face))
     (ess-assignment-face (:inherit 'font-lock-constant-face))
     (ess-%op%-face (:inherit 'ess-operator-face))
     (ess-operator-face (:inherit 'font-lock-constant-face))
     (ess-numbers-face (:slant 'normal :inherit 'font-lock-type-face))
     (ess-function-call-face (:slant 'normal :inherit 'font-lock-function-name-face))

     ;; rest
     (buffer-menu-buffer (:weight 'bold))
     (border nil)
     (browse-url-button (:inherit 'link))
     (c-annotation-face (:inherit 'font-lock-constant-face))
     (child-frame-border nil)
     (comint-highlight-input (:weight 'bold))
     (comint-highlight-prompt (:inherit 'minibuffer-prompt))
     (edebug-enabled-breakpoint (:inherit 'highlight))
     (edebug-disabled-breakpoint (:extend t :background dark-cyan))
     (elisp-shorthand-font-lock-face (:foreground lighter-cyan :inherit 'font-lock-keyword-face))
     (escape-glyph        (:foreground higher-purple))
     (eldoc-highlight-function-argument (:inherit 'bold))
     (file-name-shadow (:inherit 'shadow))
     (glyphless-char (:height 0.6))
     (holiday (:background dark-orange))
     (helpful-heading (:weight 'bold))
     (help-key-binding    (:foreground high-orange :background grey4 :box (:line-width 1 :color grey6)))
     (header-line-highlight (:inherit 'mode-line-highlight))
     (help-argument-name (:inherit 'italic))
     (help-for-help-header (:height 1.26))
     (Info-quoted (:inherit 'fixed-pitch-serif))
     (mm-command-output (:foreground green))
     (mm-uu-extract (:extend t :foreground neutral15 :background dark-green))
     (minimap-active-region (:background grey10))
     (mouse nil)
     (mouse-drag-and-drop-region (:inherit 'region))
     (menu nil)
     (next-error (:inherit 'region))
     (next-error-message (:extend t :inherit 'highlight))
     (olivetti-fringe (:inherit 'fringe))
     (read-multiple-choice-face (:weight 'bold :inherit 'underline))
     (rmail-highlight (:inherit 'highlight))
     (rmail-header-name (:inherit 'font-lock-function-name-face))
     (scroll-bar nil)
     (separator-line (:height 0.1 :background neutral5))
     (tab-line (:height 0.9 :foreground bg :background neutral15 :inherit 'variable-pitch))
     (tool-bar (:box (:line-width 1 :style 'released-button) :foreground bg :background neutral11))
     (tabulated-list-fake-header (:weight 'bold :underline t :overline t))
     (tooltip (:foreground bg :background neutral15 :inherit 'variable-pitch))
     )

    (custom-theme-set-variables
       (quote ,name)
       `(ansi-color-names-vector
         [,red
          ,olive
          ,orange
          ,purple
          ,yellow
          ,green
          ,cyan]))))

(provide 'battery)
