(require 'autothemer)

(defmacro battery-deftheme (name description greys contrasts)
  `(autothemer-deftheme
    ,name
    ,description
    ,(append
      '((((class color) (min-colors #xFFFFFF))))
      '((neutral0  "#101010")
        (neutral1  "#191919")
        (neutral2  "#262524")
        (neutral3  "#353231")
        (neutral4  "#403c3a")
        (neutral5  "#504845")
        (neutral6  "#635852")
        (neutral7  "#7b6c61")
        (neutral8  "#958172")
        (neutral9  "#a89984")
        (neutral10 "#bdae93")
        (neutral11 "#d2c3a5")
        (neutral12 "#e7d8b3")
        (neutral13 "#f2e4ba")
        (neutral14 "#faedc9")
        (neutral15 "#fef5d8"))
      greys
      '((darker-red      "#67191b")
        (darker-orange   "#572e1a")
        (darker-yellow   "#423818")
        (darker-olive    "#302f16")
        (darker-green    "#183815")
        (darker-cyan     "#1a2d1e")
        (darker-purple   "#462929")

        (dark-red        "#be241e")
        (dark-orange     "#ac4003")
        (dark-yellow     "#a57109")
        (dark-olive      "#746f06")
        (dark-green      "#24601c")
        (dark-cyan       "#2b5434")
        (dark-purple     "#a63445")

        (red             "#e83437")
        (orange          "#d6580e")
        (yellow          "#d09420")
        (olive           "#98952a")
        (green           "#3f9f32")
        (cyan            "#689e69")
        (purple          "#b16262")

        (light-red       "#fc5356")
        (light-orange    "#fc823c")
        (light-yellow    "#fac240")
        (light-olive     "#b5ba25")
        (light-green     "#5ac04e")
        (light-cyan      "#8ec07c")
        (light-purple    "#ed8585")

        (lighter-red     "#fca39c")
        (lighter-orange  "#fca765")
        (lighter-yellow  "#edd76d")
        (lighter-olive   "#dfe26c")
        (lighter-green   "#a2ea98")
        (lighter-cyan    "#aed8a0")
        (lighter-purple  "#f7b4b4"))
      contrasts)

    ((default             (:background bg :foreground fg))
     (button              (:underline t :weight 'bold :foreground yellow))
     (cursor              (:background fg))
     (mode-line           (:background neutral10 :foreground neutral2 :box (:line-width 1 :color neutral15 :style 'released-button)))
     (mode-line-inactive  (:inherit 'mode-line))
     (fringe              (:background bg))
     (hl-line             (:background bg))
     (region              (:background grey5)) ;;selection
     (secondary-selection (:background grey6))
     (minibuffer-prompt   (:background bg :foreground high-green :bold t))
     (vertical-border     (:foreground grey7))
     (internal-border     (:background grey7))
     (window-divider      (:foreground grey8))
     (link                (:foreground high-yellow :underline t))
     (shadow              (:foreground grey8))

     ;; Basic faces
     (error               (:foreground red :bold t))
     (success             (:foreground high-olive :bold t))
     (warning             (:foreground high-yellow :bold t))
     (alert-low-face      (:foreground high-cyan))
     (trailing-whitespace (:background red))
     (escape-glyph        (:foreground cyan))
     (header-line         (:background grey7 :foreground grey13 :box nil :inherit nil))
     (highlight           (:background grey4 :foreground fg))
     (homoglyph           (:foreground yellow))
     (match               (:foreground grey0 :background cyan))

     (lighter-yellow (:background lighter-yellow))

     ;; Font lock (syntax highlighting)
     (font-lock-builtin-face        (:foreground high-cyan))
     (font-lock-constant-face       (:foreground high-purple :bold nil))
     (font-lock-comment-face        (:foreground grey8))
     (font-lock-function-name-face  (:foreground high-yellow :bold nil))
     (font-lock-keyword-face        (:foreground high-red))
     (font-lock-string-face         (:foreground high-olive))
     (font-lock-variable-name-face  (:foreground high-yellow))
     (font-lock-type-face           (:foreground high-orange))
     (font-lock-warning-face        (:foreground high-red :bold t))
     (font-lock-preprocessor-face   (:foreground high-cyan))
     (font-lock-negation-char-face  (:foreground high-red))

     (tuareg-font-lock-interactive-directive-face (:foreground high-cyan))
     (tuareg-font-lock-operator-face (:foreground grey11))
     (tuareg-font-lock-governing-face (:foreground high-red))
     (tuareg-font-double-semicolon-face (:foreground high-red))
     (tuareg-font-lock-module-face (:foreground high-yellow))

     (line-number               (:foreground grey10 :background bg))
     (line-number-current-line  (:foreground high-orange :background grey3))

     ;; company-mode
     (company-scrollbar-bg                 (:background grey5))
     (company-scrollbar-fg                 (:background bg))
     (company-tooltip                      (:background bg))
     (company-tooltip-annotation           (:foreground high-green))
     (company-tooltip-annotation-selection (:inherit 'company-tooltip-annotation))
     (company-tooltip-selection            (:foreground high-purple :background grey5))
     (company-tooltip-common               (:foreground high-orange :underline t))
     (company-tooltip-common-selection     (:foreground high-orange :underline t))
     (company-preview-common               (:foreground grey13))
     (company-preview                      (:background high-orange))
     (company-preview-search               (:background high-cyan))
     (company-template-field               (:foreground grey0 :background high-yellow))
     (company-echo-common                  (:foreground red))

     ;; org-mode
     (org-latex-and-related     (:foreground lower-yellow))
     ; (org-document-info-keyword ())
     (org-document-title        (:foreground high-purple))
     (org-block-begin-line      (:foreground grey6 :background grey0))
     (org-block-end-line        (:foreground grey6 :background grey0))
     (org-special-keyword       (:foreground grey8))
     ; (org-property-value        ())
     (org-document-info         (:foreground orange))
     (org-meta-line             (:foreground grey8))
     ; (org-verbatim ())
     (org-level-1  (:foreground high-orange))
     (org-level-2  (:foreground high-red))
     (org-level-3  (:foreground high-yellow))
     (org-level-4  (:foreground high-olive))
     (org-level-5  (:foreground high-cyan))
     (org-level-6  (:foreground high-purple))
     (org-level-7  (:foreground green))
     (org-level-8  (:foreground orange))
     (org-drawer   (:foreground grey7))
     (org-tag      (:weight 'bold))
     (org-link     (:underline (:style 'line :color grey9)))
     (org-done     (:foreground grey6))
     (org-todo     (:foreground high-yellow))
     ; (org-code     ())
     (org-table    ( :foreground grey12))
     ; (org-block    ())
     (org-footnote ( :foreground yellow))
     ; (org-checkbox ())
     (org-checkbox-statistics-todo (:foreground higher-purple))
     (org-checkbox-statistics-done (:foreground high-cyan))

     (jupyter-repl-input-prompt  (:foreground olive))
     (jupyter-repl-output-prompt (:foreground red))

     (dashboard-items-face  (:foreground grey13))
     (dashboard-main-button (:foreground grey13 :bold t))

     ;; orderless
     (orderless-match-face-0 (:foreground high-cyan :bold t))
     (orderless-match-face-1 (:foreground high-olive :bold t))
     (orderless-match-face-2 (:foreground high-orange :bold t))
     (orderless-match-face-3 (:foreground high-yellow :bold t))

     (rainbow-delimiters-depth-1-face   (:foreground cyan))
     (rainbow-delimiters-depth-2-face   (:foreground purple))
     (rainbow-delimiters-depth-3-face   (:foreground green))
     (rainbow-delimiters-depth-4-face   (:foreground orange))
     (rainbow-delimiters-depth-5-face   (:foreground cyan))
     (rainbow-delimiters-depth-6-face   (:foreground purple))
     (rainbow-delimiters-depth-7-face   (:foreground green))
     (rainbow-delimiters-depth-8-face   (:foreground orange))
     (rainbow-delimiters-depth-9-face   (:foreground cyan))
     (rainbow-delimiters-depth-10-face  (:foreground purple))
     (rainbow-delimiters-depth-11-face  (:foreground green))
     (rainbow-delimiters-depth-12-face  (:foreground orange))
     (rainbow-delimiters-unmatched-face (:foreground high-red))

     ;; eshell
     (eshell-prompt        (:foreground cyan))
     (eshell-ls-archive    (:foreground grey7))
     (eshell-ls-backup     (:foreground grey7))
     (eshell-ls-clutter    (:foreground orange :bold t))
     (eshell-ls-directory  (:foreground yellow))
     (eshell-ls-executable (:bold t))
     (eshell-ls-missing    (:foreground high-red :bold t))
     (eshell-ls-product    (:foreground low-red))
     (eshell-ls-readonly   (:foreground grey7))
     (eshell-ls-special    (:foreground high-yellow :bold t))
     (eshell-ls-symlink    (:foreground high-red))
     (eshell-ls-unreadable (:foreground high-red :bold t))

     ;; lsp
     (lsp-face-highlight-textual        (:background grey6))
     (lsp-face-highlight-read           (:background grey6))
     (lsp-face-highlight-write          (:background grey6))
     (lsp-face-semhl-constant           (:foreground cyan))
     (lsp-face-semhl-deprecated         (:foreground cyan))
     (lsp-face-semhl-enummember         (:foreground cyan))
     (lsp-face-semhl-field              (:foreground cyan))
     (lsp-face-semhl-field-static       (:foreground cyan))
     (lsp-face-semhl-function           (:foreground cyan))
     (lsp-face-semhl-method             (:foreground cyan))
     (lsp-face-semhl-namespace          (:foreground cyan))
     (lsp-face-semhl-preprocessor       (:foreground cyan))
     (lsp-face-semhl-static-method      (:foreground cyan))
     (lsp-face-semhl-type-class         (:foreground cyan))
     (lsp-face-semhl-type-enum          (:foreground cyan))
     (lsp-face-semhl-type-primitive     (:foreground cyan))
     (lsp-face-semhl-type-template      (:foreground cyan))
     (lsp-face-semhl-type-typedef       (:foreground cyan))
     (lsp-face-semhl-variable           (:foreground cyan))
     (lsp-face-semhl-variable-local     (:foreground cyan))
     (lsp-face-semhl-variable-parameter (:foreground cyan))
     (lsp-lens-face                     (:foreground cyan))
     (lsp-lens-mouse-face               (:foreground cyan))
     (lsp-ui-doc-background             (:foreground cyan))
     (lsp-ui-doc-header                 (:foreground cyan))
     (lsp-ui-doc-url                    (:foreground cyan))
     (lsp-ui-peek-filename              (:foreground cyan))
     (lsp-ui-peek-footer                (:foreground cyan))
     (lsp-ui-peek-header                (:foreground cyan))
     (lsp-ui-peek-highlight             (:foreground cyan))
     (lsp-ui-peek-line-number           (:foreground cyan))
     (lsp-ui-peek-list                  (:foreground cyan))
     (lsp-ui-peek-peek                  (:foreground cyan))
     (lsp-ui-peek-selection             (:foreground cyan))
     (lsp-ui-sideline-code-action       (:foreground cyan))
     (lsp-ui-sideline-current-symbol    (:foreground cyan))
     (lsp-ui-sideline-symbol            (:foreground cyan))
     (lsp-ui-sideline-symbol-info       (:foreground cyan))

     ;; flymake
     (flymake-error (:underline (:style 'wave :color high-red)))
     (flymake-warning (:underline (:style 'wave :color high-cyan)))

     ;; flyspell
     (flyspell-incorrect (:underline (:style 'wave :color red)))

     ;; git-gutter
     (git-gutter:added (:foreground higher-green :weight 'bold))
     (git-gutter:modified (:foreground higher-purple :weight 'bold))
     (git-gutter:deleted (:foreground higher-red :weight 'bold))

     ;; whitespace
     (whitespace-tab      (:background bg :foreground grey6))
     (whitespace-space    (:background bg :foreground grey6))
     (whitespace-hspace   (:background bg :foreground grey6))
     (whitespace-newline  (:background bg :foreground grey6))
     (whitespace-line     (:background bg :foreground grey6))
     (whitespace-empty    (:background bg :foreground grey6))
     (whitespace-indentation      (:background bg :foreground grey6))
     (whitespace-big-indent       (:background bg :foreground grey6))
     (whitespace-space-after-tab  (:background bg :foreground grey6))
     (whitespace-space-before-tab       (:background high-red))
     (whitespace-missing-newline-at-eof (:background high-red))
     (whitespace-trailing               (:background high-red))

     ;; diff
     (diff-header      (:extend t :background grey3))
     (diff-hunk-header (:inherit 'diff-header))
     (diff-file-header (:weight 'bold :extend t :background grey4))
     (diff-changed nil)
     (diff-removed (:extend t :background lower-red   :inherit 'diff-changed))
     (diff-added   (:extend t :background lower-green :inherit 'diff-changed))
     (diff-refine-changed nil)
     (diff-refine-removed (:background low-red   :inherit 'diff-refine-changed))
     (diff-refine-added   (:background low-green :inherit 'diff-refine-changed))

     ; (diff-index (:inherit 'diff-file-header))
     ; (diff-changed-unspecified (:extend t :background grey0 :inherit 'diff-changed))
     ; (diff-indicator-removed (:foreground high-red :inherit 'diff-removed))
     ; (diff-indicator-added (:foreground green :inherit 'diff-added))
     ; (diff-indicator-changed (:foreground light-olive :inherit 'diff-changed))
     ; (diff-function (:inherit 'diff-header))
     ; (diff-context (:extend t))
     ; (diff-nonexistent (:inherit 'diff-file-header))
     ; (diff-error (:weight 'bold :foreground red :background grey15))

     ;; other
     (mini-modeline-mode-line  (:background low-olive :height 0.14 :box nil))
     (yeet/mode-line-meow-mode (:foreground higher-olive :background grey4))

     (show-paren-match    (:background cyan))
     (help-key-binding    (:foreground high-orange :background grey4 :box (:line-width 1 :color grey6)))
     (escape-glyph        (:foreground higher-purple))
     (dired-broken-symlink (:foreground grey1 :background red :bold t))
     (dired-symlink (:foreground cyan))
     (dired-directory (:foreground orange))

     (isearch (:foreground grey13 :background lower-purple))
     (isearch-fail (:foreground grey13 :background lower-red))
     (isearch-group-1 (:foreground high-red :background low-purple))
     (isearch-group-2 (:foreground high-red :background low-purple))
     (lazy-highlight (:background grey4))

     (query-replace (:inherit 'isearch))

     (sly-warning-face (:underline (:color high-orange)))

     (minimap-active-region (:background grey10))

     (meow-normal-indicator (:foreground darker-olive))
     (meow-insert-indicator (:foreground darker-red))
     (meow-beacon-indicator (:foreground darker-cyan))
     (meow-keypad-indicator (:foreground darker-purple))
     (meow-motion-indicator (:foreground darker-green))
     (meow-search-indicator (:foreground darker-yellow))

     (vterm-color-cyan    (:foreground cyan))
     (vterm-color-green   (:foreground olive))
     (vterm-color-black   (:foreground grey2))
     (vterm-color-blue    (:foreground orange))
     (vterm-color-red     (:foreground red))
     (vterm-color-yellow  (:foreground yellow))
     (vterm-color-white   (:foreground grey11))
     (vterm-color-magenta (:foreground purple))

     (csv-separator-face (:foreground high-cyan))

     (eglot-highlight-symbol-face (:inherit 'bold))
     (eglot-mode-line (:foreground low-purple :weight 'bold :inherit 'font-lock-constant-face))
     (eglot-diagnostic-tag-unnecessary-face (:inherit 'shadow))
     (eglot-diagnostic-tag-deprecated-face (:strike-through t :inherit 'shadow))

     (realgud-debugger-running     (:weight 'bold :foreground high-green))
     (realgud-debugger-not-running (:inherit 'font-lock-warning-face))
     (realgud-overlay-arrow1       (:inherit 'realgud-debugger-running))
     (realgud-overlay-arrow2       (:weight 'bold :foreground grey15))
     (realgud-overlay-arrow3       (:foreground grey6))
     (debugger-running             (:weight 'bold :foreground high-green))
     (debugger-not-running (:inherit 'font-lock-warning-face))
     (realgud-bp-enabled-face       (:weight 'bold :foreground high-red))
     (realgud-bp-line-enabled-face  (:box (:color high-red)))
     (realgud-bp-disabled-face      (:weight 'bold :foreground grey10))
     (realgud-bp-line-disabled-face (:box (:color grey10)))
     (realgud-line-numbers (:inherit 'font-lock-variable-name-face))
     (realgud-file-name (:inherit 'font-lock-preprocessor-face))
     (realgud-backtrace-number (:weight 'bold :foreground bg))

     ;; ansi-color
     (ansi-color-red     (:foreground red    :background red))
     (ansi-color-green   (:foreground olive  :background olive))
     (ansi-color-yellow  (:foreground yellow :background yellow))
     (ansi-color-blue    (:foreground orange :background orange))
     (ansi-color-magenta (:foreground purple :background purple))
     (ansi-color-cyan    (:foreground cyan   :background cyan))

     (ansi-color-bright-red     (:foreground light-red    :background light-red))
     (ansi-color-bright-green   (:foreground light-olive  :background light-olive))
     (ansi-color-bright-yellow  (:foreground light-yellow :background light-yellow))
     (ansi-color-bright-blue    (:foreground light-orange :background light-orange))
     (ansi-color-bright-magenta (:foreground light-purple :background light-purple))
     (ansi-color-bright-cyan    (:foreground light-cyan   :background light-cyan))
     )
    (custom-theme-set-variables
       (quote ,name)
       `(ansi-color-names-vector
         [,red
          ,olive
          ,orange
          ,purple
          ,yellow
          ,green
          ,cyan]))))

(provide 'battery)
